SESSION 3 - NumPy Advanced (Part 3: Matrix Ops & Manipulation)Topics Covered:Mathematical operationsAddition, subtraction, multiplication, divisionElement-
wise vs matrix multiplicationMatrix operationsdot(), matmul()transpose, TStatistical functionsmean, median, std, var, sumLinear algebra modulenp.linalg.inv(),
det(), eig()Array manipulationreshape(), flatten(), ravel()concatenate(), stack(), split()



In [1]:
import numpy as np



TASKS

1. Create two NumPy arrays representing the daily step counts of two friends over a week and use element-wise addition, subtraction, multiplication, and division to compare their activity levels.


In [8]:
step_count_1 = np.random.randint(0,10000,20)
print(step_count_1)
step_count_2 = np.random.randint(0,10000,20)
print(step_count_2)

print("----")

print(f"Addition :-\n{step_count_1 + step_count_2}")

print(f"Subsctraction :- \n{step_count_1 - step_count_2}")

print(f"Muiltiplication:- \n{step_count_1 - step_count_2}")

print(f"Divison :- \n{step_count_1/step_count_2}")


[3334 7911 7183 5928 3751  552  434 2697 1388 1474 4015 3517 5767 6380
 9437 3791 1386 6152 6056  967]
[7899 9654 9757 9595 3224 1756 7389 5217 3618 6394 2710 1180 7503 8771
 4685  947 4111 4335 1002 8130]
----
Addition :-
[11233 17565 16940 15523  6975  2308  7823  7914  5006  7868  6725  4697
 13270 15151 14122  4738  5497 10487  7058  9097]
Subsctraction :- 
[-4565 -1743 -2574 -3667   527 -1204 -6955 -2520 -2230 -4920  1305  2337
 -1736 -2391  4752  2844 -2725  1817  5054 -7163]
Muiltiplication:- 
[-4565 -1743 -2574 -3667   527 -1204 -6955 -2520 -2230 -4920  1305  2337
 -1736 -2391  4752  2844 -2725  1817  5054 -7163]
Divison :- 
[0.42207874 0.81945308 0.7361894  0.61782178 1.16346154 0.3143508
 0.05873596 0.51696377 0.38363737 0.23052862 1.48154982 2.98050847
 0.76862588 0.7273971  2.01430096 4.0031679  0.33714425 1.41914648
 6.04391218 0.11894219]



2. Simulate a Spotify-like 'Recommended Songs' feature: Given two 3x3 matrices representing user-song interaction scores (user preferences and song popularity), use dot() and matmul() to compute the final
recommendation matrix and explain the difference between the two results.


In [2]:
matrix1 = np.random.rand(3,3)
print(matrix1)
print("----")
matrix2 = np.random.rand(3,3)
print(matrix2)

print("----")

dotmul = np.dot(matrix1 , matrix2)
print(dotmul)
print("----")
mulmat = np.matmul(matrix1 , matrix2)
print(mulmat)


## i don't understand this what is the difference --(it is said that upto 3d it is same above 3d its starts differentialing and matmul is better at 3d+)

[[0.24296732 0.73477489 0.79828124]
 [0.14769153 0.61105913 0.00168174]
 [0.80338466 0.1580001  0.57337327]]
----
[[0.13862784 0.86974989 0.85658687]
 [0.30280053 0.4447498  0.55983117]
 [0.29779232 0.4651798  0.5064414 ]]
----
[[0.49389428 0.90945609 1.02375516]
 [0.206004   0.40100543 0.46945227]
 [0.32996015 1.0357359  1.06700209]]
----
[[0.49389428 0.90945609 1.02375516]
 [0.206004   0.40100543 0.46945227]
 [0.32996015 1.0357359  1.06700209]]



3. Given a 4x4 NumPy matrix representing the pixel brightness of a small Instagram image, use transpose (T) to rotate the image and then calculate the mean, median, standard deviation, and variance of the pixel values.


In [ ]:
pixel_matrix = np.random.randint(0,256,(4,4))
print(pixel_matrix)
## i am not able to visulize 3-D shape it will looks like this if declareed through manual way 
# [[[255,0,0], [255,0,0], [255,0,0]],
#  [[255,0,0], [255,0,0], [255,0,0]],
#  [[255,0,0], [255,0,0], [255,0,0]]]

rotate1 = np.transpose(pixel_matrix)

print(rotate1)

print(np.mean(rotate1))
print(np.median(rotate1))
print(np.std(rotate1))

[[ 26  97  54 100]
 [ 12 127  54 227]
 [100 164  45 232]
 [135 248 169  70]]
[[ 26  12 100 135]
 [ 97 127 164 248]
 [ 54  54  45 169]
 [100 227 232  70]]
116.25
100.0
72.21019664839585



4. Take a 3x3 NumPy matrix representing a Zomato restaurant rating correlation grid and use np.linalg.inv(), np.linalg.det(), and np.linalg.eig() to compute its inverse, determinant, and eigenvalues/eigenvectors.

        Hint: If the matrix is not invertible, modify one value and try again.



Determinant  → Can this matrix be inverted?

Inverse      → Matrix equivalent of division

Eigenvector  → Direction that doesn't change

Eigenvalue   → Amount of stretching in that direction


Why AI/ML Uses Them
Determinant

Used to:

Check if matrices are invertible
Multivariate Gaussian distributions
Inverse

Used in:

Linear Regression
Solving systems of equations
Eigenvalues/Eigenvectors

Used in:

PCA (Principal Component Analysis)
Face Recognition
Recommendation Systems
Deep Learning
Dimensionality Reduction

In [ ]:
image = np.random.randint(0, 5, (5, 5))

print(image)
print("-------------------\n -----------------")
print(np.linalg.inv(image))
print("-------------------")
print(np.linalg.det(image))
print("-------------------")
print(np.linalg.eig(image))

[[2 0 0 3 0]
 [4 2 1 1 2]
 [4 1 4 1 0]
 [1 1 0 2 0]
 [0 4 2 2 0]]
-------------------
[[-1.00000000e+00  0.00000000e+00  2.72727273e-01  1.90909091e+00
  -5.45454545e-01]
 [-1.00000000e+00  0.00000000e+00  9.09090909e-02  1.63636364e+00
  -1.81818182e-01]
 [ 1.00000000e+00  0.00000000e+00  7.93016446e-17 -2.00000000e+00
   5.00000000e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.81818182e-01 -1.27272727e+00
   3.63636364e-01]
 [ 2.00000000e+00  5.00000000e-01 -5.45454545e-01 -3.81818182e+00
   8.40909091e-01]]
-------------------
44.00000000000005
-------------------
EigResult(eigenvalues=array([ 6.1863051 +0.j        , -1.        +0.j        ,
       -0.81026853+0.j        ,  2.81198172+0.93310989j,
        2.81198172-0.93310989j]), eigenvectors=array([[ 0.11602928+0.j        , -0.20851441+0.j        ,
         0.24518747+0.j        , -0.17517605+0.22791877j,
        -0.17517605-0.22791877j],
       [ 0.56178089+0.j        , -0.41702883+0.j        ,
         0.40027747+0.j        ,  0.072


5. Create a NumPy array of shape (2, 6) representing the number of orders placed on Swiggy in two cities over 6 days. Reshape it to (3, 4), flatten it, split it into two equal parts, and then stack both parts vertically.

### Interview takeaway

np.array_split() returns a list of arrays. If the resulting arrays have different sizes, np.array() cannot combine them into a regular NumPy array because NumPy arrays require all rows to have the same length.

In [36]:
array1 = np.random.randint(0,1000,12).reshape(2,6)
print(array1)
print("-------------------\n now rshape it to 3,4-----------------")
# now rshape it to 3,4
array1 = array1.reshape(3,4)
print(array1)
print("-------------------\n flatten and ravel methods -----------------")
# flatten and ravel methods - flatten is a copy , ravel is view (memory refernce this will alter data on both the lists )

array2 = array1.flatten()
print(array2)
print("-------------------\n -now split is into two equal par----------------")
# now split is into two equal parts -  there are two types of split one is eual parts other is eual parts if less elemt them last one will be of remaining elemts 

splitarray = np.split(array2 ,2)
splitarray1 = np.array_split(array1 , 5) 

splitarray = np.array(splitarray)
### splitarray1 = np.array(splitarray1)


print(newarray)
# here output was diffeent because the split works different with 1d and 2d
print(splitarray)
print("-------------------\n -----------------")
print(type(splitarray))
print("-------------------\n -----------------")
print(splitarray1)
print("-------------------\nstacking vertically vstack -----------------")

## stacking vertically can done by two ways one is vstack , and other is concatenation row contanation
stacking1 = np.vstack(splitarray)
print(stacking1)
print("-------------------\nstacking vertically vstack -----------------")
stacking1 = np.vstack(splitarray1)
print(stacking1)
print("-------------------\n concatenations -----------------")
stacking2 = np.concatenate(splitarray, 0)
print(stacking2)
print("-------------------\n -----------------")

stacking2 = np.concatenate(splitarray1 ,0)
print(stacking2)
print("-------------------\n -----------------")

[[434 941 994 864 781 371]
 [635 978 594 361 697 316]]
-------------------
 now rshape it to 3,4-----------------
[[434 941 994 864]
 [781 371 635 978]
 [594 361 697 316]]
-------------------
 flatten and ravel methods -----------------
[434 941 994 864 781 371 635 978 594 361 697 316]
-------------------
 -now split is into two equal par----------------
[[144 220 979 320 371  74]
 [124 744  92 182 606 964]]
[[434 941 994 864 781 371]
 [635 978 594 361 697 316]]
-------------------
 -----------------
<class 'numpy.ndarray'>
-------------------
 -----------------
[array([[434, 941, 994, 864]], dtype=int32), array([[781, 371, 635, 978]], dtype=int32), array([[594, 361, 697, 316]], dtype=int32), array([], shape=(0, 4), dtype=int32), array([], shape=(0, 4), dtype=int32)]
-------------------
stacking vertically vstack -----------------
[[434 941 994 864 781 371]
 [635 978 594 361 697 316]]
-------------------
stacking vertically vstack -----------------
[[434 941 994 864]
 [781 371 635 978]

Important concept

concatenate(..., axis=0) → stack vertically (rows)

concatenate(..., axis=1) → stack horizontally (columns)

For axis=1, all arrays must have the same number of rows.

Your empty arrays have 0 rows, so NumPy refuses.