SESSION 1- NumPy Foundations (Part 1: Arrays & Creation)Topics Covered:What is NumPy & why it's essential for Data Sciencelnstalling & importing
NumPyCreating NumPy arraysnp.array()np.arange()np.linspace()np.zeros(), np.ones()np.full(), np.eye()Array attributesshape, ndim, size, dtype,
itemsizeConversion between Python lists ? NumPy arraysUnderstanding contiguous memory layout

### TASKS

1. Install NumPy in your Python environment using pip, then create a Python file called insta_likes.py and import numpy as np at the top.



In [1]:
# pip install numpy 

import numpy as np



2. Create a NumPy array called followers using np.array0 that stores the follower counts for 5 Instagram influencers: [1200, 15000, 67000, 340000, 1250000]. Print the array, its shape, number of dimensions, and data type.



In [2]:
followers = np.array([1200,15000,67000,340000,1250000])

print(followers)

print(np.shape(followers))

print(np.ndim(followers))

print(type(followers))


[   1200   15000   67000  340000 1250000]
(5,)
1
<class 'numpy.ndarray'>



3. Use np.arange0) to generate an array of order IDs for 10 consecutive Zomato orders starting from 101. Print the array and its size.


In [8]:
order = np.arange(101,111,1)
print(order)
np.size(order)

[101 102 103 104 105 106 107 108 109 110]


10


4. Create a 3x3 NumPy array using np.eye() to represent a 'like' identity matrix for a new Spotify playlist feature. Print the matrix and explain what the diagonal values represent in a comment.



In [11]:
np.eye(3)


# the diaognal 1 in this context refer that a one song is like and no other available songs are being like similary for 2 and 3 , in broder way 
# if i say that if person 1 like song 1 he doesn;t like 2 and 3 , same with if like2 not likes 1 and 3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


5. Convert a Python list of cricket scores [45, 67, 120, 89, 54] to a NumPy array, then use the .itemsize attribute to print how many bytes each score takes in memory.

    Hint: Use np.array0 for conversion and .itemsize for memory size.

In [14]:
cricket_score = [45,67,120,89,54]

cricket_score_array = np.array(cricket_score)
print(cricket_score_array)

cricket_score_array.itemsize

[ 45  67 120  89  54]


8