SESSION 2 - NumPy Intermediate (Part 2: Indexing, Slicing, Broadcasting)Topics Covered:Indexing in 1D, 2D, and nD arraysSlicing arrays: [:], [start:end],
[start:end:step]selecting rows & columnsBoolean indexingFancy indexingBroadcasting rulesScalar-to-array broadcastingArray-to-array broadcastingPractical

examples:Masking out negative valuesBroadcasting for feature scaling


Fancy indeing means that accessing the elemts thrpugh index directly

In [1]:
import numpy as np

### TASKS

1. Create a 2D NumPy array representing the ratings (out of 5) given by 4 users to 5 different food items on Zomato. Use slicing to extract the ratings given by the second and third users only.


In [10]:
np.random.seed(42)
# row = user 
# column = 5 food items 
ratings = np.random.randint(0,6,20).reshape(4,5)
print(ratings)
## -- > ratings[[1,2],] this is using fancy indexing
ratings[1:3,] #--> this is slicing

[[3 4 2 4 4]
 [1 2 2 2 4]
 [3 2 5 4 1]
 [3 5 5 1 3]]


array([[1, 2, 2, 2, 4],
       [3, 2, 5, 4, 1]], dtype=int32)



2. Given a NumPy array of daily steps tracked for 10 days, use boolean indexing to select only the days where the steps were greater than 8000.

        Hint: Use an array like steps = np.array([7500, 8200, 9000, ... ]) and apply a boolean condition.


In [ ]:
np.random.seed(48)
steps = np.random.randint(0,10000,10)
print(steps)

np.where(steps > 8000)
# now i will give this to a list of user and can get user names with 8000+ steps 

[2611 9553 7088  966  454 9506  348 9430 2975 3886]


(array([1, 5, 7]),)


3. Create a NumPy array of IPL team scores for 8 matches. Use fancy indexing to select the scores from matches 2, 5, and 7, and print them.



In [ ]:
np.random.seed(42)
team_score = np.random.randint(0,200,8)
print(team_score)
team_score[[2,5,7]] # --> fancy indexing means accessing usinn the list or array

[102 179  92  14 106  71 188  20]


array([92, 71, 20], dtype=int32)


4. Suppose you have a NumPy array of product prices from Flipkart. Use broadcasting to apply a 10% discount to all prices and print the new array.

        Constraint: Do not use any loops.


In [29]:
np.random.seed(42)
product_price = np.random.randint(100,1000,100)
print(product_price)

site_wise_discount = product_price * 0.90
print(site_wise_discount)

[202 535 960 370 206 171 800 120 714 221 566 314 430 558 187 472 199 971
 763 230 761 408 869 443 591 513 905 485 291 376 260 559 413 121 352 847
 956 660 574 158 610 781 575 799 882 289 786 662 975 666 343 931 604 230
 584 918 746 120 940 266 373 487 700 415 113 341 876 445 664 997 439 191
 466 554 527 608 875 134 305 180 661 971 487 101 489 665 205 871 921 576
 802 501 829 655 261 301 369 962 915 370]
[181.8 481.5 864.  333.  185.4 153.9 720.  108.  642.6 198.9 509.4 282.6
 387.  502.2 168.3 424.8 179.1 873.9 686.7 207.  684.9 367.2 782.1 398.7
 531.9 461.7 814.5 436.5 261.9 338.4 234.  503.1 371.7 108.9 316.8 762.3
 860.4 594.  516.6 142.2 549.  702.9 517.5 719.1 793.8 260.1 707.4 595.8
 877.5 599.4 308.7 837.9 543.6 207.  525.6 826.2 671.4 108.  846.  239.4
 335.7 438.3 630.  373.5 101.7 306.9 788.4 400.5 597.6 897.3 395.1 171.9
 419.4 498.6 474.3 547.2 787.5 120.6 274.5 162.  594.9 873.9 438.3  90.9
 440.1 598.5 184.5 783.9 828.9 518.4 721.8 450.9 746.1 589.5 234.9 270.9
 332.1 86


5. Given a NumPy array of user ratings (can be negative, zero, or positive) for songs on Spotify, use boolean masking to set all negative ratings to zero, keeping other ratings unchanged.


In [34]:
User_rating = np.random.randint(-5,5,100)
print(User_rating)

User_rating[User_rating <0] = 0
print(User_rating)

[-2  1 -4 -3 -5 -1 -5  2 -5 -5 -4 -4  0  1 -1 -5 -5 -3 -4 -1  4  0  1 -2
  1  2 -5  0  2 -1 -2 -4  0  0 -5  3  0 -3 -2 -2 -3  4 -3 -3 -2  1 -2  3
 -5  2  1 -4  2 -5  3  3 -4  1  4 -3  1  4  3 -2 -5 -4 -5 -1 -1  1  3  3
 -3 -3 -3 -2  2  0  2 -5  2 -2 -5  2 -2  0  2 -2 -3  3 -3  3 -4 -4 -4  0
 -3  3 -2 -5]
[0 1 0 0 0 0 0 2 0 0 0 0 0 1 0 0 0 0 0 0 4 0 1 0 1 2 0 0 2 0 0 0 0 0 0 3 0
 0 0 0 0 4 0 0 0 1 0 3 0 2 1 0 2 0 3 3 0 1 4 0 1 4 3 0 0 0 0 0 0 1 3 3 0 0
 0 0 2 0 2 0 2 0 0 2 0 0 2 0 0 3 0 3 0 0 0 0 0 3 0 0]
